version: 2

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    id: "Remarkable Paper Pro"
    main: .
    binary: goMarkableStream
    goos:
      - linux
    goarch:
      - arm64
    goarm:
      - "7"
  - env:
      - CGO_ENABLED=0
    id: "Remarkable 2"
    main: .
    binary: goMarkableStream
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"

archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: owulveryck
    name: gomarkablestream
